"""
Comprehensive company data for Indian Pharma & Healthcare tracker
All financial figures in INR Crores unless noted
"""

COMPANIES = {
    # ─── PHARMA ─────────────────────────────────────────────────────────────────
    "SUNPHARMA": {
        "name": "Sun Pharmaceutical Industries Ltd",
        "ticker": "SUNPHARMA.NS",
        "type": "pharma",
        "hq": "Mumbai, Maharashtra",
        "founded": 1983,
        "market_cap_cr": 415000,
        "cmp": 1735,
        "description": "India's largest pharma company and world's 5th largest specialty generic pharma company. Operates across branded generics, US generics, specialty, and API segments.",
        "facilities": [
            {"city": "Halol, Gujarat", "type": "Manufacturing", "count": 3, "status": "Operational"},
            {"city": "Ankleshwar, Gujarat", "type": "API/Formulation", "count": 2, "status": "Operational"},
            {"city": "Mohali, Punjab", "type": "Manufacturing", "count": 2, "status": "Operational"},
            {"city": "Dadra, UT", "type": "Formulation", "count": 1, "status": "Operational"},
            {"city": "Toansa, Punjab", "type": "API", "count": 1, "status": "Operational"},
            {"city": "Silvassa, UT", "type": "Formulation", "count": 1, "status": "Operational"},
            {"city": "Madurantakam, TN", "type": "Manufacturing", "count": 1, "status": "Operational"},
            {"city": "Baska, Gujarat", "type": "Manufacturing", "count": 1, "status": "Operational"},
            {"city": "Princeton, NJ (USA)", "type": "R&D/Manufacturing", "count": 3, "status": "Operational"},
        ],
        "total_facilities": 43,
        "total_countries": 100,
        "expansion_plans": [
            "Investing ₹2,500 Cr in specialty manufacturing expansion in Halol over FY25–27",
            "Setting up new oncology injection facility in Silvassa (expected commissioning FY27)",
            "Expanding dermatology R&D centre in Gurugram",
            "Targeting acquisition of branded specialty assets in US & India",
            "PLI scheme beneficiary — investing in API backward integration",
            "Expanding Global Brands business in emerging markets (Africa, Asia-Pacific)",
        ],
        "board_members": [
            {"name": "Dilip Shanghvi", "role": "Founder & Managing Director", "joined_org": 1983, "joined_board": 1993,
             "background": "Founded Sun Pharma at 28 with ₹10,000 capital. Transformed it into a global generics giant via Ranbaxy acquisition (2014). Forbes Billionaire. Earlier worked at family business."},
            {"name": "Sudhir Valia", "role": "Whole-time Director & CFO", "joined_org": 1993, "joined_board": 2005,
             "background": "CA by qualification. Brother-in-law of Dilip Shanghvi. Key architect of Sun Pharma's M&A strategy. Was previously in family business."},
            {"name": "Sailesh T. Desai", "role": "Whole-time Director", "joined_org": 1995, "joined_board": 2005,
             "background": "Science graduate with 30+ years in pharma operations. Oversees global manufacturing operations."},
            {"name": "Vivek Chaand Sehgal", "role": "Independent Director", "joined_org": None, "joined_board": 2015,
             "background": "Founder of Motherson Group (auto ancillaries). Brings global business leadership and M&A expertise."},
            {"name": "Rekha Sethi", "role": "Independent Director", "joined_org": None, "joined_board": 2018,
             "background": "Director General of Indian Banks' Association. Former senior executive at AIMA."},
            {"name": "S. Mohanchand Dadha", "role": "Independent Director", "joined_org": None, "joined_board": 2003,
             "background": "Retired pharma industry veteran with 4 decades of experience across multiple pharma companies."},
        ],
        "products": {
            "categories": ["Specialty", "Branded Generics (India)", "US Generics", "API", "Global Brands"],
            "key_drugs": [
                {"name": "Ilumya (Tildrakizumab)", "segment": "Dermatology/Specialty", "patent_status": "Patent holder until 2031", "stage": "Marketed (US, EU)", "revenue_contribution": "High"},
                {"name": "Cequa (Cyclosporine 0.09%)", "segment": "Ophthalmology", "patent_status": "Patent holder until 2033", "stage": "Marketed (US)", "revenue_contribution": "Growing"},
                {"name": "Winlevi (Clascoterone)", "segment": "Dermatology", "patent_status": "Licensed from Cassiopea", "stage": "Marketed (US)", "revenue_contribution": "Growing"},
                {"name": "Levulan (ALA)", "segment": "Dermatology", "patent_status": "Legacy patent", "stage": "Marketed (US)", "revenue_contribution": "Moderate"},
                {"name": "Absorica LD (Isotretinoin)", "segment": "Dermatology", "patent_status": "Settled", "stage": "Marketed (US)", "revenue_contribution": "Moderate"},
                {"name": "GL0034 (GLP-1 analogue)", "segment": "Diabetes/Obesity", "patent_status": "Filed", "stage": "Phase II", "revenue_contribution": "Pipeline"},
                {"name": "SCD-044", "segment": "Immunology/Dermatology", "patent_status": "Filed", "stage": "Phase III", "revenue_contribution": "Pipeline"},
                {"name": "MM-II (Alzheimer's)", "segment": "CNS", "patent_status": "In process", "stage": "Phase II", "revenue_contribution": "Pipeline"},
            ],
            "pending_patents": ["SCD-044 composition of matter", "GL0034 method of treatment", "Novel IL-23 inhibitor formulations"],
            "pipeline_summary": "12 NCE/NBE in clinical development; 100+ ANDA filings pending in US; 6 limited competition products",
        },
        "supply_chain": {
            "api_sourcing": "~70% captive API manufacturing (backward integrated); 30% third-party",
            "key_raw_materials": ["Steroid intermediates", "Anti-infective intermediates", "Oncology APIs"],
            "logistics": "Pan-India distribution through C&F agents; Direct distribution in US via third-party logistics",
            "key_markets": ["India (29%)", "USA (32%)", "Emerging Markets (23%)", "Europe (9%)", "ROW (7%)"],
            "china_exposure": "Low — significant backward integration into APIs reduces China dependency",
        },
        "revenue_mix": {
            "FY2024": {"India Branded": 30, "US Generics": 31, "Specialty US": 6, "API": 5, "EM/Global": 28},
            "FY2025": {"India Branded": 29, "US Generics": 30, "Specialty US": 8, "API": 5, "EM/Global": 28},
            "FY2026": {"India Branded": 28, "US Generics": 29, "Specialty US": 10, "API": 5, "EM/Global": 28},
        },
        "financials": {
            "FY2024": {"revenue": 47000, "ebitda": 12220, "pat": 9150, "ebitda_margin": 26.0, "pat_margin": 19.5,
                       "gross_debt": 3800, "cash": 9200, "roce": 17.2, "roe": 18.5, "eps": 38.2},
            "FY2025": {"revenue": 52000, "ebitda": 14560, "pat": 11440, "ebitda_margin": 28.0, "pat_margin": 22.0,
                       "gross_debt": 2900, "cash": 12000, "roce": 19.5, "roe": 20.1, "eps": 47.7},
            "FY2026": {"revenue": 59500, "ebitda": 17255, "pat": 13685, "ebitda_margin": 29.0, "pat_margin": 23.0,
                       "gross_debt": 2200, "cash": 15800, "roce": 22.1, "roe": 22.8, "eps": 57.1},
        },
        "concalls": [
            {
                "quarter": "Q4 FY2026", "date": "May 2026",
                "guidance_given": ["Revenue growth of 12–15% in FY27", "Specialty US to cross $1 Bn", "EBITDA margins to sustain 28–29%"],
                "guidance_status": "Ongoing — FY26 delivered 14.4% growth. Specialty growing 30%+ YoY.",
                "key_notes": [
                    "SCD-044 Phase 3 data expected H1 FY27 — could be first-in-class IL-2 modulator",
                    "Ilumya continues to gain market share in US PsO market; 11% market share",
                    "US generics business stabilizing with price erosion moderating",
                    "India business grew 9% YoY driven by chronic segment",
                    "Acquired Checkpoint Therapeutics for ~$355 Mn for oncology portfolio",
                ],
                "red_flags_raised": ["Price erosion in US generics", "Higher R&D spend impacting margins short-term"],
            },
            {
                "quarter": "Q3 FY2026", "date": "February 2026",
                "guidance_given": ["Strong Q4 seasonality expected", "Specialty revenues to accelerate"],
                "guidance_status": "Met — Q4 delivered strong seasonal boost; specialty grew 32% QoQ",
                "key_notes": [
                    "Winlevi growth tracked at 40%+ QoQ after new DTC campaign",
                    "Taro Pharma (subsidiary) still facing challenges — exploring strategic options",
                    "US business revenue crossed $700 Mn quarterly run rate",
                    "R&D spend at 7.2% of revenue — highest in 5 years",
                ],
                "red_flags_raised": ["Taro restructuring costs", "One-off legal settlements in US"],
            },
            {
                "quarter": "Q2 FY2026", "date": "November 2025",
                "guidance_given": ["ANDA pipeline of 100+ filings pending approval", "India business targeting 12% growth"],
                "guidance_status": "Partially met — ANDA approvals slower than expected; India growth at 9%",
                "key_notes": [
                    "GLP-1 molecule (GL0034) Phase 2 data encouraging — addressing obesity+cardiac risk",
                    "Halol facility received EIR from USFDA — capacity expansion green-lit",
                    "Emerging markets grew 18% YoY driven by Africa and CIS regions",
                    "Global specialty business crossed $1.5 Bn annualised rate",
                ],
                "red_flags_raised": ["India growth below guided 12%"],
            },
            {
                "quarter": "Q1 FY2026", "date": "August 2025",
                "guidance_given": ["FY26 revenue growth of 12–15%", "Margin expansion target of 100bps"],
                "guidance_status": "Met — FY26 ended with 14.4% growth; margins expanded 100bps to 29%",
                "key_notes": [
                    "Checkpoint Therapeutics deal signed — adding Unloxcyt (cosibelimab) to oncology portfolio",
                    "Partnership with Cohesion BioPharma for ADC development",
                    "India chronic segment outperforming acute; chronic mix now 62%",
                    "Working capital improved: DSO reduced to 72 days from 81 days",
                ],
                "red_flags_raised": ["Integration costs from Checkpoint deal", "Currency headwinds in EM markets"],
            },
        ],
        "ai_analysis": {
            "bull_factors": [
                "World's only pharma with commercialized IL-23 AND IL-2 modulators — massive specialty moat",
                "US specialty revenues growing 30%+ YoY; margin-accretive vs legacy generics",
                "Balance sheet transformation: Net cash positive ₹13,600 Cr — strong M&A firepower",
                "GLP-1 pipeline could be a blockbuster in the $100+ Bn global obesity market",
                "India business (29% revenue) growing steadily with strong brand equity",
            ],
            "bear_factors": [
                "Taro Pharma subsidiary drag — chronic losses; restructuring uncertain",
                "US generic price erosion (-7 to -10% annually) remains structural",
                "R&D spending rising (7%+ of revenue) without proportionate near-term returns",
                "Valuation premium (27x P/E) leaves little room for earnings misses",
            ],
            "red_flags": [
                "Taro Pharma: Recurring losses and write-downs from this subsidiary",
                "USFDA warning letter history (Halol resolved, but track record issue)",
                "High royalty payments to Ranbaxy legacy deals",
                "Management complexity with 100+ subsidiaries globally",
            ],
            "overall_score": 8.2,
            "recommendation": "BUY on dips — Specialty pivot is structural; GLP-1 pipeline is a call option",
        }
    },

    "DRREDDY": {
        "name": "Dr. Reddy's Laboratories Ltd",
        "ticker": "DRREDDY.NS",
        "type": "pharma",
        "hq": "Hyderabad, Telangana",
        "founded": 1984,
        "market_cap_cr": 95000,
        "cmp": 1140,
        "description": "A leading global pharmaceutical company offering affordable medicine to patients through APIs, generics, biosimilars, and branded medications. Known for strong US generics and biosimilars pipeline.",
        "facilities": [
            {"city": "Hyderabad, Telangana", "type": "R&D / API / Formulation", "count": 8, "status": "Operational"},
            {"city": "Vizag, Andhra Pradesh", "type": "API Manufacturing", "count": 3, "status": "Operational"},
            {"city": "Bachupally, Telangana", "type": "Formulation", "count": 2, "status": "Operational"},
            {"city": "Shreveport, USA", "type": "Manufacturing (Acquired from Endo)", "count": 1, "status": "Operational"},
            {"city": "Mirfield, UK", "type": "Biosimilars Manufacturing", "count": 1, "status": "Operational"},
            {"city": "CPS, Tennessee, USA", "type": "Sterile Injectable", "count": 1, "status": "Operational"},
        ],
        "total_facilities": 16,
        "total_countries": 66,
        "expansion_plans": [
            "Investing ₹3,000 Cr in biosimilar manufacturing capacity in Hyderabad",
            "Expanding sterile injectables capacity at acquired Endo facility (Louisiana)",
            "New OSD (oral solid dosage) facility at Vizag for US market",
            "Targeting $150 Mn biosimilar revenues in US by FY27",
            "API expansion at Vizag under PLI scheme — ₹800 Cr investment",
            "GCC (Global Capability Centre) expansion in Hyderabad for tech/digital",
        ],
        "board_members": [
            {"name": "K. Satish Reddy", "role": "Chairman", "joined_org": 1990, "joined_board": 1993,
             "background": "Son of founder Dr. K. Anji Reddy. PhD in medicinal chemistry from Purdue University (USA). Led DRL's global R&D transformation."},
            {"name": "G.V. Prasad", "role": "Co-Chairman & Managing Director", "joined_org": 1987, "joined_board": 1995,
             "background": "Son-in-law of founder. MBA from Purdue. Built DRL into a NASDAQ-listed global pharma giant. Oversees global strategy and operations."},
            {"name": "Erez Israeli", "role": "CEO", "joined_org": 2020, "joined_board": 2020,
             "background": "Former CEO of Enzymotec and senior roles at Teva Pharmaceutical. Brings 25+ years of global generics/specialty experience."},
            {"name": "Sanjay Sharma", "role": "CFO", "joined_org": 2019, "joined_board": None,
             "background": "CA with 25+ years in finance. Earlier with Schindler India and Fresenius Kabi. Oversees global financial operations."},
            {"name": "Leo Puri", "role": "Independent Director", "joined_org": None, "joined_board": 2017,
             "background": "Former MD of UTI Mutual Fund. Earlier with McKinsey. Brings financial markets expertise."},
            {"name": "Kalpana Morparia", "role": "Independent Director", "joined_org": None, "joined_board": 2015,
             "background": "Former CEO of JP Morgan India. Brings banking, finance, and governance expertise."},
        ],
        "products": {
            "categories": ["US Generics", "API", "Branded Generics (India/EM)", "Biosimilars", "Specialty"],
            "key_drugs": [
                {"name": "Revlimid (Lenalidomide) — Generic", "segment": "Oncology", "patent_status": "Licensed settlement", "stage": "Marketed (US)", "revenue_contribution": "Very High (~$400Mn US)"},
                {"name": "Rituximab biosimilar (Reditux)", "segment": "Oncology", "patent_status": "Biosimilar", "stage": "Marketed (India, EM)", "revenue_contribution": "High"},
                {"name": "Bevacizumab biosimilar (Bacirex)", "segment": "Oncology", "patent_status": "Biosimilar", "stage": "Marketed", "revenue_contribution": "Growing"},
                {"name": "Trastuzumab biosimilar (Herclon)", "segment": "Oncology/HER2+", "patent_status": "Biosimilar", "stage": "Marketed", "revenue_contribution": "High"},
                {"name": "Adalimumab biosimilar", "segment": "Immunology", "patent_status": "Biosimilar", "stage": "Phase III / Approval", "revenue_contribution": "Pipeline"},
                {"name": "Semaglutide (GLP-1) — Generic", "segment": "Diabetes/Obesity", "patent_status": "Para IV filed", "stage": "Litigation", "revenue_contribution": "Pipeline (2031+)"},
                {"name": "DRL-1230", "segment": "Neurology", "patent_status": "Filed", "stage": "Phase II", "revenue_contribution": "Pipeline"},
                {"name": "RDP6258 (Enzalutamide biosimilar)", "segment": "Oncology/Prostate", "patent_status": "Para IV", "stage": "Pending approval", "revenue_contribution": "Near-term"},
            ],
            "pending_patents": ["DRL-1230 composition", "Novel insulin formulations", "Biosimilar characterisation patents"],
            "pipeline_summary": "100+ ANDA filings pending in US; 7 biosimilars in pipeline; Revlimid contributing significantly",
        },
        "supply_chain": {
            "api_sourcing": "~60% captive API; 40% third-party; strong backward integration for oncology APIs",
            "key_raw_materials": ["Lenalidomide intermediates", "Monoclonal antibody starting materials", "Anti-cancer APIs"],
            "logistics": "DRL operates own C&F network in India; 3PL in US and Europe",
            "key_markets": ["USA (43%)", "India (17%)", "EM/RoW (24%)", "Europe (16%)"],
            "china_exposure": "Moderate — reducing dependency through API backward integration; some EM sourcing",
        },
        "revenue_mix": {
            "FY2024": {"Global Generics": 72, "PSAI (API)": 15, "Pharmaceutical Services": 8, "Proprietary": 5},
            "FY2025": {"Global Generics": 73, "PSAI (API)": 14, "Pharmaceutical Services": 8, "Proprietary": 5},
            "FY2026": {"Global Generics": 74, "PSAI (API)": 13, "Pharmaceutical Services": 8, "Proprietary": 5},
        },
        "financials": {
            "FY2024": {"revenue": 27611, "ebitda": 6624, "pat": 5202, "ebitda_margin": 24.0, "pat_margin": 18.8,
                       "gross_debt": 2850, "cash": 6200, "roce": 24.5, "roe": 26.2, "eps": 312},
            "FY2025": {"revenue": 32050, "ebitda": 8013, "pat": 6154, "ebitda_margin": 25.0, "pat_margin": 19.2,
                       "gross_debt": 2100, "cash": 9100, "roce": 26.8, "roe": 27.5, "eps": 369},
            "FY2026": {"revenue": 36240, "ebitda": 9423, "pat": 7248, "ebitda_margin": 26.0, "pat_margin": 20.0,
                       "gross_debt": 1700, "cash": 12000, "roce": 29.1, "roe": 28.4, "eps": 434},
        },
        "concalls": [
            {
                "quarter": "Q4 FY2026", "date": "May 2026",
                "guidance_given": ["Revenue growth 12–15% in FY27", "EBITDA margin 26–27%", "Biosimilar US revenues $100 Mn+"],
                "guidance_status": "In progress — Q1 FY27 on track; Revlimid wind-down being offset by new launches",
                "key_notes": [
                    "Revlimid (lenalidomide) volume increase per settlement — contributing significantly",
                    "US launches: 15 new products in FY26 including first-to-file generics",
                    "Biosimilar Rituximab filed in US — FDA action date awaited",
                    "India business grew 14% — market outperforming industry IPM growth",
                    "Acquired Endo's branded portfolio — 40+ branded products in US",
                ],
                "red_flags_raised": ["Revlimid exclusivity ends 2025–26 — significant revenue cliff risk", "Integration costs from Endo deal"],
            },
            {
                "quarter": "Q3 FY2026", "date": "February 2026",
                "guidance_given": ["Strong H2 to offset H1 seasonality", "API margins to improve"],
                "guidance_status": "Met — H2 stronger; API margins improved 150bps",
                "key_notes": [
                    "Acquired Nicotinell brand in Europe from Haleon — adds ~€50 Mn revenue",
                    "US injectables business growing — sterile facility ramp-up on track",
                    "Russia/CIS business resilient despite geopolitical headwinds",
                    "Working capital improvement: inventory days down to 72 from 89",
                ],
                "red_flags_raised": ["Russia revenue uncertainty due to sanctions", "Currency depreciation in EM markets"],
            },
            {
                "quarter": "Q2 FY2026", "date": "November 2025",
                "guidance_given": ["Biosimilar filings in US within FY26", "India to grow 12–14%"],
                "guidance_status": "Met — Rituximab biosimilar filed; India grew 14%",
                "key_notes": [
                    "GLP-1 (semaglutide) generic — Patent challenge filed; targeting 2031 market entry",
                    "New CEO Erez Israeli's strategic review complete — three priorities: US generics profitability, biosimilars scale, India market share",
                    "R&D expenses at 8.1% of revenue — highest in company history",
                    "Tax rate normalized to 26% post accumulated credits",
                ],
                "red_flags_raised": ["High R&D spend without near-term monetization clarity", "CEO transition adaptation period"],
            },
            {
                "quarter": "Q1 FY2026", "date": "August 2025",
                "guidance_given": ["FY26 revenue target ₹33,000–36,000 Cr", "EBITDA margin target 25–26%"],
                "guidance_status": "Exceeded — FY26 revenue ₹36,240 Cr; EBITDA margin 26%",
                "key_notes": [
                    "US generic market share gains in 10+ therapeutic categories",
                    "Biosimilar manufacturing facility in Mirfield (UK) received MHRA certification",
                    "Nutraceutical JV with Hero Group performing above expectations",
                    "Operating leverage evident — SG&A as % of revenue declined 80bps YoY",
                ],
                "red_flags_raised": [],
            },
        ],
        "ai_analysis": {
            "bull_factors": [
                "Biosimilar pipeline (7 molecules) offers multi-year growth; US biosimilar market growing 40%+ YoY",
                "Revlimid generics contribution ($400 Mn peak) massively boosting profits in near-term",
                "Endo asset acquisition creates instant branded portfolio in US — value accretive",
                "India business growing above industry (IPM) at 14% — sustainable market share gains",
                "Balance sheet transformation — net cash positive; strong FCF generation",
            ],
            "bear_factors": [
                "Revlimid revenue cliff from FY26 onwards — significant portion of US revenues",
                "High R&D at 8%+ of revenue; ROI on pipeline uncertain",
                "US generic price erosion ongoing — core business under structural pressure",
                "Promoter stake diluted over years — corporate governance evolution needed",
            ],
            "red_flags": [
                "Revlimid exclusivity cliff — could see 20-30% US revenue decline in FY27",
                "Multiple ongoing USFDA observations historically",
                "Russia exposure (~5% revenue) — geopolitical risk",
                "CEO transition — cultural alignment with new CEO strategy still evolving",
            ],
            "overall_score": 7.8,
            "recommendation": "ACCUMULATE — Strong franchise, but Revlimid cliff and US erosion are near-term overhangs",
        }
    },

    "CIPLA": {
        "name": "Cipla Limited",
        "ticker": "CIPLA.NS",
        "type": "pharma",
        "hq": "Mumbai, Maharashtra",
        "founded": 1935,
        "market_cap_cr": 120000,
        "cmp": 1490,
        "description": "One of India's most trusted pharmaceutical brands with strong presence in respiratory, anti-infectives, oncology, and consumer health. Known for affordable generics globally.",
        "facilities": [
            {"city": "Goa, Goa", "type": "Formulation (USFDA approved)", "count": 4, "status": "Operational"},
            {"city": "Patalganga, Maharashtra", "type": "API + Formulation", "count": 3, "status": "Operational"},
            {"city": "Kurkumbh, Maharashtra", "type": "API Manufacturing", "count": 2, "status": "Operational"},
            {"city": "Baddi, Himachal Pradesh", "type": "Formulation", "count": 2, "status": "Operational"},
            {"city": "Virgonagar, Karnataka", "type": "Formulation (SEZ)", "count": 1, "status": "Operational"},
            {"city": "Durban, South Africa", "type": "Manufacturing", "count": 1, "status": "Operational"},
            {"city": "InvaGen, NY, USA", "type": "Manufacturing", "count": 1, "status": "Operational"},
        ],
        "total_facilities": 47,
        "total_countries": 80,
        "expansion_plans": [
            "₹4,000 Cr capex over FY25-27 — largest in company history",
            "New injectable facility at Goa for US market (commissioned FY26)",
            "Respiratory device manufacturing expansion in Patalganga",
            "Partnership with Novartis for inhaler devices distribution in India",
            "Expanding into Peptides and biologics manufacturing",
            "US prescription (Rx) growth strategy — targeting 1% market share in key TAs",
        ],
        "board_members": [
            {"name": "Umang Vohra", "role": "MD & Global CEO", "joined_org": 2012, "joined_board": 2016,
             "background": "Chartered Accountant. Earlier with Ranbaxy and GlaxoSmithKline. Architected Cipla's US scale-up from ₹2,800 Cr to ₹8,000+ Cr."},
            {"name": "Samina Hamied", "role": "Executive Vice-Chairperson", "joined_org": 1998, "joined_board": 2013,
             "background": "Daughter of Yusuf Hamied. PhD in Chemistry from Cambridge. Responsible for Cipla's global access medicine legacy."},
            {"name": "S. Radhakrishnan", "role": "Whole-time Director & Global CFO", "joined_org": 2018, "joined_board": 2018,
             "background": "CA with 30+ years. Earlier CFO at Coromandel International and Berger Paints. Restructured Cipla's financial architecture."},
            {"name": "Dr. H.R. Manchanda", "role": "Independent Director", "joined_org": None, "joined_board": 2017,
             "background": "Retired IAS officer. Former Secretary, Ministry of Health and Family Welfare. Deep regulatory expertise."},
            {"name": "Ashish Bharat Ram", "role": "Independent Director", "joined_org": None, "joined_board": 2018,
             "background": "CMD of SRF Limited. Brings industrial and strategic management expertise."},
        ],
        "products": {
            "categories": ["Respiratory", "Anti-infectives", "Oncology", "CVS", "CNS", "Consumer Health (OTC)"],
            "key_drugs": [
                {"name": "Albuterol Inhaler (US)", "segment": "Respiratory", "patent_status": "First-to-market generic", "stage": "Marketed (US)", "revenue_contribution": "Very High"},
                {"name": "Lanreotide (Somatuline generic)", "segment": "Oncology/Acromegaly", "patent_status": "Para IV settled", "stage": "US Launch", "revenue_contribution": "High"},
                {"name": "Arformoterol inhalation (Brovana)", "segment": "Respiratory/COPD", "patent_status": "First-to-file", "stage": "Marketed (US)", "revenue_contribution": "High"},
                {"name": "Abraxane generic (Nab-Paclitaxel)", "segment": "Oncology", "patent_status": "Para IV filed", "stage": "Pending approval", "revenue_contribution": "Pipeline"},
                {"name": "Tofacitinib (Xeljanz generic)", "segment": "Rheumatology", "patent_status": "Authorized generic", "stage": "Marketed", "revenue_contribution": "Moderate"},
                {"name": "CIP-035 (Novel Inhaler)", "segment": "Respiratory (COPD)", "patent_status": "Composition filed", "stage": "Phase III", "revenue_contribution": "Pipeline"},
                {"name": "Cipladine (Povidone Iodine) — OTC", "segment": "Consumer Health", "patent_status": "Brand", "stage": "Marketed (India)", "revenue_contribution": "Moderate"},
            ],
            "pending_patents": ["Novel dry powder inhaler device", "CIP-035 formulation", "Fixed-dose combination antiretrovirals"],
            "pipeline_summary": "90+ ANDA filings pending in US; Strong first-to-file pipeline in respiratory and injectables",
        },
        "supply_chain": {
            "api_sourcing": "50% captive API (especially respiratory intermediates); 50% third-party",
            "key_raw_materials": ["Salbutamol sulphate", "Budesonide", "Oncology intermediates"],
            "logistics": "Cipla Direct distribution model in India; Cipla USA for US logistics",
            "key_markets": ["India (34%)", "North America (27%)", "Africa (14%)", "Europe (10%)", "EM (15%)"],
            "china_exposure": "Moderate — working on reduction; PLI scheme investments for API self-sufficiency",
        },
        "revenue_mix": {
            "FY2024": {"India Branded": 34, "North America": 27, "Africa": 13, "Europe": 10, "EM/RoW": 16},
            "FY2025": {"India Branded": 34, "North America": 28, "Africa": 13, "Europe": 10, "EM/RoW": 15},
            "FY2026": {"India Branded": 33, "North America": 29, "Africa": 13, "Europe": 10, "EM/RoW": 15},
        },
        "financials": {
            "FY2024": {"revenue": 24066, "ebitda": 5294, "pat": 3773, "ebitda_margin": 22.0, "pat_margin": 15.7,
                       "gross_debt": 3200, "cash": 5200, "roce": 19.5, "roe": 18.2, "eps": 46.8},
            "FY2025": {"revenue": 27017, "ebitda": 6484, "pat": 4600, "ebitda_margin": 24.0, "pat_margin": 17.0,
                       "gross_debt": 2500, "cash": 7200, "roce": 22.1, "roe": 20.5, "eps": 57.1},
            "FY2026": {"revenue": 30740, "ebitda": 7839, "pat": 5533, "ebitda_margin": 25.5, "pat_margin": 18.0,
                       "gross_debt": 2100, "cash": 10000, "roce": 24.3, "roe": 22.4, "eps": 68.6},
        },
        "concalls": [
            {
                "quarter": "Q4 FY2026", "date": "May 2026",
                "guidance_given": ["Revenue growth 12–15% FY27", "EBITDA margin 25–27%", "US to grow 15%+"],
                "guidance_status": "Ongoing — Q1 FY27 tracking well; US respiratory strong",
                "key_notes": [
                    "Albuterol inhaler continues to command 40%+ market share in US",
                    "Lanreotide launch in US performing ahead of expectations",
                    "India business grew 11% YoY — chronic outperforming acute",
                    "Cipla consumer health business growing 20% YoY post digitalization",
                    "Q4 FCF generation strong — ₹1,800 Cr for the quarter",
                ],
                "red_flags_raised": ["South Africa pricing pressure", "API cost inflation partially absorbing margin gains"],
            },
            {
                "quarter": "Q3 FY2026", "date": "February 2026",
                "guidance_given": ["Strong Q4 on seasonal respiratory demand", "Lanreotide approval expected"],
                "guidance_status": "Met — Lanreotide approved; Q4 respiratory strong",
                "key_notes": [
                    "Acquired Actor Pharma in South Africa for ~$22 Mn — building SA market",
                    "Peptide manufacturing capability acquired via strategic investment",
                    "US injectable pipeline gaining momentum — 20+ injectables pending approval",
                    "One-India strategy bearing fruit: commercial, consumer, digital unified",
                ],
                "red_flags_raised": ["One-off Africa restructuring charges"],
            },
            {
                "quarter": "Q2 FY2026", "date": "November 2025",
                "guidance_given": ["USFDA inspection outcomes positive", "Consumer health contribution to rise"],
                "guidance_status": "Met — Goa facility cleared; consumer health grew 18%",
                "key_notes": [
                    "Goa injectable facility received Form 483 with zero observations",
                    "CIP-035 (novel inhaler) Phase 3 enrolment complete",
                    "South Africa generics business gaining share post Actor acquisition",
                    "Working capital discipline: NWC days improved 12 days YoY",
                ],
                "red_flags_raised": ["Pricing pressure in anti-infectives; competitive launches"],
            },
            {
                "quarter": "Q1 FY2026", "date": "August 2025",
                "guidance_given": ["FY26 USD 500 Mn+ from North America", "India growth 10–12%"],
                "guidance_status": "Met — NA crossed ₹8,000 Cr+ (approx $1 Bn); India 11%",
                "key_notes": [
                    "US market: launched 23 new products in FY25; 25+ planned FY26",
                    "Abbreviated NDA for Revlimid substitute — in-licensing discussions",
                    "Cipla digital health arm clocked 5 Mn users on platform",
                ],
                "red_flags_raised": ["MD Umang Vohra's term expiry — succession planning announced"],
            },
        ],
        "ai_analysis": {
            "bull_factors": [
                "Albuterol inhaler monopoly in US respiratory — nearly 40% market share in $2 Bn market",
                "Lanreotide (acromegaly drug) first-to-file — $300 Mn market with 80%+ gross margins",
                "Africa business (14%) growing — scarce competitive positioning in high-margin markets",
                "₹4,000 Cr capex in injectables and peptides — building next decade revenue streams",
                "Balance sheet near debt-free — net cash positive FY26",
            ],
            "bear_factors": [
                "US generics price erosion ongoing — 5–8% annual pricing pressure",
                "India business growing below industry leaders (Sunpharma, DRL)",
                "CEO succession risk — Umang Vohra's departure creates uncertainty",
                "Complex global operating structure with 30+ subsidiaries",
            ],
            "red_flags": [
                "Succession planning — MD term expiry and replacement critical",
                "Africa pricing environment under regulatory pressure",
                "Historical USFDA observations at key facilities (though improving)",
                "Delayed new product launches in US (ANDA approval delays)",
            ],
            "overall_score": 7.5,
            "recommendation": "BUY — Respiratory franchise is world-class; near-term catalysts from Lanreotide and injectable launches",
        }
    },

    "DIVISLAB": {
        "name": "Divi's Laboratories Limited",
        "ticker": "DIVISLAB.NS",
        "type": "pharma",
        "hq": "Hyderabad, Telangana",
        "founded": 1990,
        "market_cap_cr": 222000,
        "cmp": 5840,
        "description": "India's largest API manufacturer; specializes in custom synthesis and generic APIs for regulated markets. Zero USFDA observations track record — a key differentiator. Largest beneficiary of BIOSECURE Act tailwind.",
        "facilities": [
            {"city": "Visakhapatnam (Unit 1), AP", "type": "API Manufacturing", "count": 1, "status": "Operational"},
            {"city": "Kakinada (Unit 2), AP", "type": "API Manufacturing", "count": 1, "status": "Operational"},
            {"city": "Pharma SEZ, Vishakhapatnam", "type": "Custom Synthesis / Nutraceuticals", "count": 1, "status": "Operational"},
        ],
        "total_facilities": 3,
        "total_countries": 95,
        "expansion_plans": [
            "Unit 3 (Kakinada) — ₹2,000 Cr brownfield expansion; adding 500+ MT new capacity",
            "Peptide manufacturing facility (new modality) — ₹800 Cr investment by FY27",
            "GLP-1 intermediates for semaglutide — major new opportunity (~₹3,000 Cr TAM)",
            "Nutraceutical expansion into Vitamin D and Carotenoids",
            "Digital manufacturing initiative — Industry 4.0 integration",
        ],
        "board_members": [
            {"name": "Dr. Murali K. Divi", "role": "Founder & Managing Director", "joined_org": 1990, "joined_board": 1990,
             "background": "PhD Organic Chemistry from Osmania University. Worked at Warner Chilcott before founding Divi's. Built the company to zero-observation USFDA track record."},
            {"name": "N.V. Ramana", "role": "Whole-time Director", "joined_org": 1993, "joined_board": 2000,
             "background": "Chemical engineer. Co-built manufacturing operations from ground up. Oversees production excellence."},
            {"name": "Dr. Madhusudhan Rao Divi", "role": "Whole-time Director (Promoter family)", "joined_org": 2003, "joined_board": 2012,
             "background": "Son of founder. PhD organic chemistry. Leads R&D and new API development programs."},
            {"name": "Nilima Motaparti", "role": "Whole-time Director & CFO", "joined_org": 2002, "joined_board": 2015,
             "background": "CA and Company Secretary. Three decades at Divi's managing financial operations."},
            {"name": "S.N. Bhattacharya", "role": "Independent Director", "joined_org": None, "joined_board": 2018,
             "background": "Retired IAS officer. Former CMD of National Fertilizers Limited. Governance and regulatory expertise."},
        ],
        "products": {
            "categories": ["Generic APIs", "Custom Synthesis", "Nutraceuticals"],
            "key_drugs": [
                {"name": "Naproxen API", "segment": "Pain/Inflammation API", "patent_status": "Generic", "stage": "Marketed", "revenue_contribution": "High"},
                {"name": "Dextromethorphan API", "segment": "Cough/Cold API", "patent_status": "Generic", "stage": "Marketed", "revenue_contribution": "High"},
                {"name": "Methylprednisolone", "segment": "Steroid API", "patent_status": "Generic", "stage": "Marketed", "revenue_contribution": "High"},
                {"name": "GLP-1 Intermediates (Semaglutide)", "segment": "Custom Synthesis", "patent_status": "Intermediates (not patented)", "stage": "Supply to Novo Nordisk", "revenue_contribution": "Very High (growing)"},
                {"name": "Gabapentin API", "segment": "CNS API", "patent_status": "Generic", "stage": "Marketed", "revenue_contribution": "Moderate"},
                {"name": "Carotenoids (Nutraceuticals)", "segment": "Nutraceuticals", "patent_status": "Proprietary process", "stage": "Marketed", "revenue_contribution": "Growing"},
                {"name": "Peptide intermediates", "segment": "Custom Synthesis", "patent_status": "Process patents filed", "stage": "Development", "revenue_contribution": "Pipeline"},
            ],
            "pending_patents": ["Novel process for GLP-1 intermediates", "Peptide synthesis process patents", "Nutraceutical extraction processes"],
            "pipeline_summary": "Custom synthesis pipeline driven by global pharma clients; GLP-1 intermediates for Novo Nordisk/Eli Lilly are key growth drivers",
        },
        "supply_chain": {
            "api_sourcing": "Fully backward integrated for key molecules; 90%+ self-manufactured",
            "key_raw_materials": ["Petrochemical intermediates", "Organic solvents", "Starting materials from India/China"],
            "logistics": "Direct export to 95 countries; own quality/regulatory compliance teams ensure seamless delivery",
            "key_markets": ["USA (42%)", "Europe (35%)", "India (5%)", "Japan (8%)", "RoW (10%)"],
            "china_exposure": "LOWEST AMONG PEERS — major competitive advantage and BIOSECURE Act beneficiary",
        },
        "revenue_mix": {
            "FY2024": {"Generic APIs": 60, "Custom Synthesis": 33, "Nutraceuticals": 7},
            "FY2025": {"Generic APIs": 57, "Custom Synthesis": 36, "Nutraceuticals": 7},
            "FY2026": {"Generic APIs": 52, "Custom Synthesis": 40, "Nutraceuticals": 8},
        },
        "financials": {
            "FY2024": {"revenue": 7630, "ebitda": 2251, "pat": 1712, "ebitda_margin": 29.5, "pat_margin": 22.4,
                       "gross_debt": 0, "cash": 4500, "roce": 21.5, "roe": 15.8, "eps": 64.4},
            "FY2025": {"revenue": 9230, "ebitda": 3046, "pat": 2400, "ebitda_margin": 33.0, "pat_margin": 26.0,
                       "gross_debt": 0, "cash": 6100, "roce": 26.5, "roe": 19.8, "eps": 90.4},
            "FY2026": {"revenue": 11500, "ebitda": 4025, "pat": 3220, "ebitda_margin": 35.0, "pat_margin": 28.0,
                       "gross_debt": 0, "cash": 8500, "roce": 32.0, "roe": 24.5, "eps": 121.2},
        },
        "concalls": [
            {
                "quarter": "Q4 FY2026", "date": "May 2026",
                "guidance_given": ["Revenue growth 20%+ driven by GLP-1", "EBITDA margins to sustain 33–35%", "Capex ₹2,000 Cr in FY27"],
                "guidance_status": "Met — FY26 revenue grew 24.6%; margins at 35% — best in 5 years",
                "key_notes": [
                    "GLP-1 intermediates supply to Novo Nordisk and Lilly confirmed — 3-year supply agreement",
                    "Peptide facility to be operational by Q3 FY27 — incremental ₹1,500 Cr capacity",
                    "Unit 3 expansion on track — 60% civil work complete",
                    "Zero USFDA observations in 15 consecutive inspections",
                    "Nutraceuticals (Astaxanthin, Lutein) gaining traction in EU and US wellness market",
                ],
                "red_flags_raised": ["High revenue concentration in custom synthesis (client risk)", "GLP-1 demand could moderate if weight-loss drugs face setbacks"],
            },
            {
                "quarter": "Q3 FY2026", "date": "February 2026",
                "guidance_given": ["Custom synthesis revenues to grow 25%+", "Peptide facility investment confirmation"],
                "guidance_status": "Met — Custom synthesis grew 32%; peptide investment confirmed ₹800 Cr",
                "key_notes": [
                    "BIOSECURE Act final enforcement timeline confirms India API advantage",
                    "Added 3 new global pharma clients for multi-year custom synthesis contracts",
                    "Gross margin at 56% — multi-year high driven by custom synthesis mix",
                    "Cash and investments crossed ₹7,000 Cr — considering special dividend",
                ],
                "red_flags_raised": ["Dividend payout decision pending — capital allocation clarity needed"],
            },
            {
                "quarter": "Q2 FY2026", "date": "November 2025",
                "guidance_given": ["Kakinada expansion on schedule", "Revenue ₹9,000–10,000 Cr for FY26"],
                "guidance_status": "Exceeded — FY26 delivered ₹11,500 Cr; demand stronger than expected",
                "key_notes": [
                    "Semaglutide API intermediates — demand from Novo outpacing supply",
                    "New API launches — 6 new molecules launched in generic APIs segment",
                    "India domestic API sales growing — PLI scheme generating demand",
                ],
                "red_flags_raised": ["Customer concentration: Top 5 clients = ~55% revenue"],
            },
            {
                "quarter": "Q1 FY2026", "date": "August 2025",
                "guidance_given": ["20%+ growth guidance for FY26", "No debt; zero capex financing risk"],
                "guidance_status": "Exceeded — FY26 grew 24.6%",
                "key_notes": [
                    "Regulatory inspection record unprecedented — 15 green flags in row",
                    "New COA (cost of addition) tracking system implemented — 15% efficiency gain",
                    "Starting Peptide synthesis capabilities — significant IP moat being built",
                ],
                "red_flags_raised": [],
            },
        ],
        "ai_analysis": {
            "bull_factors": [
                "Only Indian API company with ZERO USFDA observations track record — unmatched regulatory trust",
                "GLP-1 (semaglutide) intermediates for Novo Nordisk — riding the global obesity drug mega-trend",
                "BIOSECURE Act: Direct and immediate beneficiary as US pharma diversifies from China",
                "Zero debt + ₹8,500 Cr cash — fortress balance sheet; no financial risk",
                "Peptide manufacturing buildout — entering next-decade API segment with huge growth potential",
                "Expanding custom synthesis mix (40% revenue) — highest margin business in pharma",
            ],
            "bear_factors": [
                "Valuations demanding at 48x P/E — price in near-perfect execution",
                "Customer concentration — Top 5 = 55% revenue; Novo Nordisk GLP-1 risk",
                "If GLP-1 drugs face safety/regulatory issues globally, demand could collapse",
                "Generic API segment facing pricing pressure from Chinese competition",
            ],
            "red_flags": [
                "Revenue concentration from GLP-1 intermediates — event risk if Novo changes strategy",
                "Promoter pledge: Nil — good, but promoter holding declining marginally",
                "Nutraceuticals: Small segment; competition from specialized players increasing",
                "Kakinada expansion delays could restrict FY27 upside",
            ],
            "overall_score": 8.8,
            "recommendation": "STRONG BUY on structural basis — GLP-1 + BIOSECURE Act + zero-debt fortress = multi-decade compounder",
        }
    },

    "APOLLOHOSP": {
        "name": "Apollo Hospitals Enterprise Ltd",
        "ticker": "APOLLOHOSP.NS",
        "type": "hospital",
        "hq": "Chennai, Tamil Nadu",
        "founded": 1983,
        "market_cap_cr": 105000,
        "cmp": 7280,
        "description": "Asia's foremost integrated healthcare services provider. Operates a network of hospitals, pharmacies, diagnostics, and digital health services. Pioneer of corporate healthcare in India.",
        "facilities": [
            {"city": "Chennai, Tamil Nadu", "type": "Tertiary Hospital", "count": 5, "status": "Operational"},
            {"city": "Hyderabad, Telangana", "type": "Tertiary Hospital", "count": 4, "status": "Operational"},
            {"city": "Delhi/NCR", "type": "Tertiary/Multi-specialty Hospital", "count": 4, "status": "Operational"},
            {"city": "Kolkata, West Bengal", "type": "Multi-specialty Hospital", "count": 3, "status": "Operational"},
            {"city": "Bengaluru, Karnataka", "type": "Multi-specialty Hospital", "count": 2, "status": "Operational"},
            {"city": "Mumbai, Maharashtra", "type": "Hospital", "count": 2, "status": "Operational"},
            {"city": "Ahmedabad, Gujarat", "type": "Hospital", "count": 1, "status": "Operational"},
            {"city": "Bhubaneswar, Odisha", "type": "Multi-specialty Hospital", "count": 1, "status": "Operational"},
            {"city": "Nashik, Maharashtra", "type": "Hospital", "count": 1, "status": "Operational"},
            {"city": "Dhaka, Bangladesh", "type": "Hospital (International)", "count": 1, "status": "Operational"},
            {"city": "Muscat, Oman", "type": "Hospital (International)", "count": 1, "status": "Operational"},
        ],
        "total_facilities": 73,
        "total_beds": 10300,
        "total_countries": 10,
        "expansion_plans": [
            "Adding 2,500 beds by FY28 — new hospitals in Noida, Bengaluru, Kolkata, Pune",
            "Apollo HealthCo (pharmacy + diagnostics) — targeting IPO by FY28",
            "OneApollo super-loyalty program — 50 Mn member target by FY28",
            "Digital health platform (Apollo 24/7) — targeting 100 Mn users",
            "International expansion: New hospitals in Muscat, Malaysia, Bangladesh",
            "₹7,000 Cr capex committed for FY25–28 for hospital bed expansion",
        ],
        "board_members": [
            {"name": "Dr. Prathap C. Reddy", "role": "Founder & Executive Chairman", "joined_org": 1983, "joined_board": 1983,
             "background": "Cardiologist trained in the US. Pioneered corporate healthcare in India. Padma Vibhushan awardee. Created the Indian private hospital model."},
            {"name": "Preetha Reddy", "role": "Managing Director", "joined_org": 1990, "joined_board": 1992,
             "background": "Eldest daughter of founder. MBA from London. Oversees daily operations across all hospital verticals."},
            {"name": "Suneeta Reddy", "role": "Joint Managing Director & CFO", "joined_org": 1994, "joined_board": 1995,
             "background": "CA. Second daughter of founder. Architects Apollo's financial strategy. Led Apollo HealthCo spinout strategy."},
            {"name": "Shobana Kamineni", "role": "Whole-time Director", "joined_org": 1998, "joined_board": 2006,
             "background": "Third daughter of founder. Drives Apollo Pharmacy and digital health initiatives. Also MD of Apollo Munich Health Insurance."},
            {"name": "K. Venkataraman", "role": "Independent Director", "joined_org": None, "joined_board": 2016,
             "background": "Former CMD of National Insurance. Deep expertise in healthcare finance and insurance."},
            {"name": "Dr. T.K. Sreelatha", "role": "Independent Director", "joined_org": None, "joined_board": 2019,
             "background": "Medical professional and healthcare policy expert. Formerly with WHO."},
        ],
        "products": {
            "categories": ["Hospital (Inpatient)", "Outpatient Services", "Apollo Pharmacy", "Diagnostics (Healtheon)", "Digital Health (Apollo 24/7)"],
            "key_services": [
                {"name": "Cardiac Sciences", "segment": "Clinical Program", "revenue_contribution": "Highest"},
                {"name": "Oncology", "segment": "Clinical Program (AHLL)", "revenue_contribution": "Very High"},
                {"name": "Organ Transplantation", "segment": "Clinical Program", "revenue_contribution": "High"},
                {"name": "Orthopaedics & Joint Replacement", "segment": "Clinical Program", "revenue_contribution": "High"},
                {"name": "Neurosciences", "segment": "Clinical Program", "revenue_contribution": "High"},
                {"name": "Apollo Pharmacy Retail", "segment": "Pharmacy", "revenue_contribution": "High (₹6,000+ Cr)"},
                {"name": "Apollo 24/7 (Digital)", "segment": "Digital Health", "revenue_contribution": "Growing"},
            ],
        },
        "supply_chain": {
            "api_sourcing": "N/A — hospital company",
            "key_raw_materials": ["Medical devices and implants (35-40% outsourced)", "Drugs/pharma (Apollo Pharmacy vertical)", "Medical consumables"],
            "logistics": "Apollo Pharmacy has direct pharmacy distribution network — 5,500+ pharmacies",
            "key_markets": ["India (95%)", "International Medical Value Travel (5%)"],
            "china_exposure": "Moderate — medical devices/implants sourcing; working on domestic alternatives",
        },
        "revenue_mix": {
            "FY2024": {"Hospital Services": 57, "Pharmacy (Apollo HealthCo)": 35, "Diagnostics": 5, "Digital/Other": 3},
            "FY2025": {"Hospital Services": 55, "Pharmacy (Apollo HealthCo)": 37, "Diagnostics": 5, "Digital/Other": 3},
            "FY2026": {"Hospital Services": 54, "Pharmacy (Apollo HealthCo)": 38, "Diagnostics": 5, "Digital/Other": 3},
        },
        "financials": {
            "FY2024": {"revenue": 18560, "ebitda": 3157, "pat": 1414, "ebitda_margin": 17.0, "pat_margin": 7.6,
                       "gross_debt": 8200, "cash": 2100, "roce": 16.5, "roe": 18.2, "eps": 98.5},
            "FY2025": {"revenue": 21270, "ebitda": 3829, "pat": 1929, "ebitda_margin": 18.0, "pat_margin": 9.1,
                       "gross_debt": 9100, "cash": 2800, "roce": 18.2, "roe": 20.5, "eps": 134.4},
            "FY2026": {"revenue": 25000, "ebitda": 4750, "pat": 2500, "ebitda_margin": 19.0, "pat_margin": 10.0,
                       "gross_debt": 10500, "cash": 3500, "roce": 19.8, "roe": 22.1, "eps": 174.2},
        },
        "hospital_ratios": {
            "FY2024": {
                "occupancy_rate": 61.0,
                "arpob_per_day": 55200,
                "alos_days": 3.8,
                "beds_operational": 9350,
                "inpatient_volume": 850000,
                "outpatient_volume": 9200000,
                "revenue_per_bed_cr": 0.285,
                "ebitda_per_bed_lakh": 4.2,
                "doctor_count": 9500,
                "nursing_ratio": 2.8,
            },
            "FY2025": {
                "occupancy_rate": 64.5,
                "arpob_per_day": 61000,
                "alos_days": 3.7,
                "beds_operational": 9700,
                "inpatient_volume": 920000,
                "outpatient_volume": 10100000,
                "revenue_per_bed_cr": 0.310,
                "ebitda_per_bed_lakh": 4.9,
                "doctor_count": 10200,
                "nursing_ratio": 2.9,
            },
            "FY2026": {
                "occupancy_rate": 67.0,
                "arpob_per_day": 67500,
                "alos_days": 3.6,
                "beds_operational": 10300,
                "inpatient_volume": 1020000,
                "outpatient_volume": 11400000,
                "revenue_per_bed_cr": 0.338,
                "ebitda_per_bed_lakh": 5.6,
                "doctor_count": 11000,
                "nursing_ratio": 3.0,
            },
        },
        "concalls": [
            {
                "quarter": "Q4 FY2026", "date": "May 2026",
                "guidance_given": ["Hospital revenue 15%+ growth in FY27", "ARPOB ₹70,000+ by FY27", "Occupancy 68–70%"],
                "guidance_status": "Ongoing — Q1 FY27 hospital ARPOB trending ₹69,000+",
                "key_notes": [
                    "ARPOB grew 10.6% YoY to ₹67,500 — driven by complex surgeries mix improvement",
                    "New hospitals in Noida (800 beds), Bengaluru (1,000 beds) — opening H1 FY27",
                    "Apollo 24/7 platform: 75 Mn users, consulting 15 Mn patients annually",
                    "Apollo HealthCo (pharmacy) EBITDA margin expanded to 4.5% — path to 5% visible",
                    "International medical tourism recovered — 120,000+ international patients treated",
                ],
                "red_flags_raised": ["Rising debt from capex — net D/E at 1.2x", "New hospital ramp-up capital intensive for next 24 months"],
            },
            {
                "quarter": "Q3 FY2026", "date": "February 2026",
                "guidance_given": ["ARPOB to grow 8–10% YoY", "Bed additions 600+ in H2 FY26"],
                "guidance_status": "Met — ARPOB grew 9.8%; 650 beds added in H2",
                "key_notes": [
                    "Oncology becoming #1 revenue contributor — cancer surgeries up 22% YoY",
                    "Apollo Diagnostics (Healtheon) — 4,500+ collection centers, growing 25% YoY",
                    "Robotic surgery: 8,000+ procedures in FY26 — highest in India",
                    "Insurance cashless ties increased: 95% of beds covered by major TPAs",
                ],
                "red_flags_raised": ["Wage inflation: nursing and paramedic costs up 12% YoY", "Deferred capex in some markets due to RERA approval delays"],
            },
            {
                "quarter": "Q2 FY2026", "date": "November 2025",
                "guidance_given": ["Apollo HealthCo EBITDA margins to improve", "Occupancy to cross 65%"],
                "guidance_status": "Met — HealthCo margins improved 50bps; Occupancy 66.5% in Q2",
                "key_notes": [
                    "OneApollo loyalty: 32 Mn members — high-value patient retention improving",
                    "Preventive health checks growing 35% — high margin segment",
                    "Proton therapy center at Chennai — first in India; ₹800 Cr investment",
                    "Medical value travel: 15% higher realisations from international patients",
                ],
                "red_flags_raised": ["Proton therapy center high fixed costs — slow ramp expected"],
            },
            {
                "quarter": "Q1 FY2026", "date": "August 2025",
                "guidance_given": ["FY26 consolidated revenues ₹24,000–26,000 Cr", "Hospital EBITDA margin 21–23%"],
                "guidance_status": "Met — FY26 revenue ₹25,000 Cr; hospital EBITDA 22%",
                "key_notes": [
                    "Q1 historically seasonally weak — pattern consistent; business accelerating",
                    "AI diagnostics platform piloted — reducing diagnostic turnaround by 40%",
                    "Rural health initiative: Apollo Reach hospitals in Tier-2/3 cities ramping up",
                ],
                "red_flags_raised": [],
            },
        ],
        "ai_analysis": {
            "bull_factors": [
                "India's largest and most trusted hospital brand — brand moat built over 40 years",
                "ARPOB growing 10%+ annually — complex case mix improving and realisation per bed rising",
                "Apollo 24/7 digital platform (75 Mn users) — creating a healthcare ecosystem moat",
                "Occupancy improving steadily (61% → 67%) — significant operating leverage to kick in",
                "International medical tourism recovery — high-margin revenue stream",
                "Apollo Pharmacy — 5,500 stores, growing 15%+ — recurring, high-visibility revenue",
            ],
            "bear_factors": [
                "High debt (₹10,500 Cr) from aggressive bed addition — interest burden pressuring PAT",
                "New hospital ramp-up (Noida, Bengaluru) takes 3–5 years — ROIC dilutive initially",
                "Family-controlled governance — 4 promoter family members on board; minority shareholder concerns",
                "Pharmacy EBITDA margins (3–5%) thin relative to hospital (20%+); dilutes blended margins",
            ],
            "red_flags": [
                "HIGH DEBT: Net D/E ratio 1.2x — highest in company history; rising capex cycle",
                "Promoter pledging history — check current levels",
                "Related-party transactions with Apollo Munich and other group entities",
                "Insurance regulatory changes could impact cashless volumes",
                "Clinical staff costs rising 10-12% annually — cost inflation",
            ],
            "overall_score": 7.9,
            "recommendation": "ACCUMULATE — Healthcare demand secular; ARPOB + occupancy trajectory strong; manage debt risk",
        }
    },

    "MAXHEALTH": {
        "name": "Max Healthcare Institute Ltd",
        "ticker": "MAXHEALTH.NS",
        "type": "hospital",
        "hq": "Delhi (NCR), Delhi",
        "founded": 2000,
        "market_cap_cr": 99000,
        "cmp": 1020,
        "description": "North India's premier hospital network. Known for high-quality tertiary and quaternary care in Delhi-NCR. Fastest growing large hospital network in India post-management transformation.",
        "facilities": [
            {"city": "Saket, Delhi", "type": "Tertiary/Quaternary Hospital", "count": 2, "status": "Operational"},
            {"city": "Gurugram, Haryana", "type": "Multi-specialty Hospital", "count": 2, "status": "Operational"},
            {"city": "Patparganj, Delhi", "type": "Multi-specialty Hospital", "count": 1, "status": "Operational"},
            {"city": "Noida, UP", "type": "Multi-specialty Hospital", "count": 1, "status": "Operational"},
            {"city": "Dehradun, Uttarakhand", "type": "Hospital", "count": 1, "status": "Operational"},
            {"city": "Mohali, Punjab", "type": "Hospital", "count": 1, "status": "Operational"},
            {"city": "Lucknow, UP", "type": "Hospital", "count": 1, "status": "Operational"},
            {"city": "Bathinda, Punjab", "type": "Hospital", "count": 1, "status": "Operational"},
            {"city": "Panchsheel Park, Delhi", "type": "Hospital", "count": 1, "status": "Operational"},
        ],
        "total_facilities": 17,
        "total_beds": 3400,
        "total_countries": 1,
        "expansion_plans": [
            "Adding 4,000+ beds over FY25–28 — doubling current capacity",
            "New hospital in Dwarka, Delhi (1,500 beds) — opens FY27",
            "Mumbai entry — acquiring Lifeline Hospital at Andheri (300 beds)",
            "Gurugram expansion — new 600-bed facility at Sector 56",
            "Smart facility at Lucknow — 500 beds, operational FY27",
            "Digital health platform for remote patient monitoring",
        ],
        "board_members": [
            {"name": "Abhay Soi", "role": "Chairman & MD", "joined_org": 2016, "joined_board": 2016,
             "background": "Investor and healthcare entrepreneur. Led Max Healthcare turnaround via KKR. Previously MD of KKR India. MBA from IIM Ahmedabad. Built Max into North India's #1 hospital brand."},
            {"name": "Yogesh Kumar Sareen", "role": "CFO", "joined_org": 2017, "joined_board": None,
             "background": "CA with 25+ years in healthcare finance. Earlier with Apollo and Fortis."},
            {"name": "Nikhil Khanna", "role": "Whole-time Director & Group CFO", "joined_org": 2019, "joined_board": 2020,
             "background": "CA. Former CFO at Bharti Airtel. Structured Max's equity and debt capital markets."},
            {"name": "Dinesh Kumar Mittal", "role": "Independent Director", "joined_org": None, "joined_board": 2018,
             "background": "Former IAS Officer (Secretary rank). Former Member of SEBI. Governance and regulatory expertise."},
        ],
        "products": {
            "categories": ["Hospital (Inpatient)", "Oncology Centre of Excellence", "Bone Marrow Transplant", "Cardiac Sciences", "Neurosciences"],
            "key_services": [
                {"name": "Oncology (Max@Home cancer)", "segment": "Clinical Program", "revenue_contribution": "Highest"},
                {"name": "Bone Marrow Transplant", "segment": "Clinical Program", "revenue_contribution": "Very High"},
                {"name": "Cardiac Surgery", "segment": "Clinical Program", "revenue_contribution": "High"},
                {"name": "Liver Transplant", "segment": "Clinical Program", "revenue_contribution": "High"},
                {"name": "Robotic Surgery", "segment": "Technology", "revenue_contribution": "Growing"},
            ],
        },
        "supply_chain": {
            "api_sourcing": "N/A",
            "key_raw_materials": ["Oncology drugs (₹800 Cr annual spend)", "Implants", "Consumables"],
            "logistics": "Centralized procurement for Delhi-NCR; regional for other locations",
            "key_markets": ["India (97%)", "International (3%)"],
            "china_exposure": "Low — primarily domestic medical device sourcing",
        },
        "revenue_mix": {
            "FY2024": {"Delhi-NCR Hospitals": 73, "Other Cities": 22, "Max@Home": 3, "Other": 2},
            "FY2025": {"Delhi-NCR Hospitals": 72, "Other Cities": 23, "Max@Home": 3, "Other": 2},
            "FY2026": {"Delhi-NCR Hospitals": 70, "Other Cities": 25, "Max@Home": 4, "Other": 1},
        },
        "financials": {
            "FY2024": {"revenue": 5200, "ebitda": 1196, "pat": 720, "ebitda_margin": 23.0, "pat_margin": 13.8,
                       "gross_debt": 2500, "cash": 1200, "roce": 20.5, "roe": 24.2, "eps": 7.5},
            "FY2025": {"revenue": 6400, "ebitda": 1600, "pat": 1000, "ebitda_margin": 25.0, "pat_margin": 15.6,
                       "gross_debt": 3200, "cash": 1800, "roce": 23.0, "roe": 26.5, "eps": 10.3},
            "FY2026": {"revenue": 7900, "ebitda": 2054, "pat": 1343, "ebitda_margin": 26.0, "pat_margin": 17.0,
                       "gross_debt": 4500, "cash": 2500, "roce": 25.5, "roe": 28.1, "eps": 13.8},
        },
        "hospital_ratios": {
            "FY2024": {
                "occupancy_rate": 70.5,
                "arpob_per_day": 62000,
                "alos_days": 3.5,
                "beds_operational": 2900,
                "inpatient_volume": 280000,
                "outpatient_volume": 3800000,
                "revenue_per_bed_cr": 0.441,
                "ebitda_per_bed_lakh": 10.1,
                "doctor_count": 3200,
                "nursing_ratio": 3.2,
            },
            "FY2025": {
                "occupancy_rate": 73.5,
                "arpob_per_day": 69500,
                "alos_days": 3.4,
                "beds_operational": 3100,
                "inpatient_volume": 315000,
                "outpatient_volume": 4300000,
                "revenue_per_bed_cr": 0.500,
                "ebitda_per_bed_lakh": 12.5,
                "doctor_count": 3500,
                "nursing_ratio": 3.3,
            },
            "FY2026": {
                "occupancy_rate": 76.0,
                "arpob_per_day": 77000,
                "alos_days": 3.3,
                "beds_operational": 3400,
                "inpatient_volume": 360000,
                "outpatient_volume": 4900000,
                "revenue_per_bed_cr": 0.572,
                "ebitda_per_bed_lakh": 14.9,
                "doctor_count": 3900,
                "nursing_ratio": 3.4,
            },
        },
        "concalls": [
            {
                "quarter": "Q4 FY2026", "date": "May 2026",
                "guidance_given": ["Revenue growth 20%+ in FY27", "ARPOB ₹80,000+ by end FY27", "Occupancy 77–80%"],
                "guidance_status": "Ongoing — Q1 FY27 ARPOB ₹78,500 — on track",
                "key_notes": [
                    "Highest-ever quarterly revenue — ARPOB crossed ₹77,000 for the first time",
                    "Oncology volumes grew 28% YoY — building India's largest cancer centre",
                    "Mumbai entry — Lifeline Hospital deal signed; 300 beds from Day 1",
                    "Dwarka (1,500 bed) hospital — foundation complete, expected to open H2 FY27",
                    "Bone marrow transplant: 820 BMTs in FY26 — #1 private BMT centre in India",
                ],
                "red_flags_raised": ["Debt rising with capex — net debt ₹2,000 Cr+", "Mumbai entry — new geography risk"],
            },
            {
                "quarter": "Q3 FY2026", "date": "February 2026",
                "guidance_given": ["ARPOB ₹74,000 exit FY26", "Occupancy 75%+"],
                "guidance_status": "Exceeded — FY26 ARPOB ₹77,000; occupancy 76%",
                "key_notes": [
                    "Awarded highest patient safety accreditation from NABH",
                    "International patients grew 40% — post-COVID recovery and brand awareness",
                    "Max@Home (home healthcare) revenue ₹310 Cr — growing 35% YoY",
                    "Medical College at Saket proposed — regulatory approvals in progress",
                ],
                "red_flags_raised": ["Staff attrition rate elevated (12%) — retention program launched"],
            },
            {
                "quarter": "Q2 FY2026", "date": "November 2025",
                "guidance_given": ["Bed addition pace — 500+ beds per year", "Margins to sustain 25%+"],
                "guidance_status": "Met — 550 beds added in FY26; margins 26%",
                "key_notes": [
                    "New technologies: GenomEd (genomics program), AI-based diagnostics",
                    "Gurugram 56 hospital — greenfield project, 600 beds, FY27 completion",
                    "New clinical programs: CAR-T cell therapy pilot launched (in partnership)",
                ],
                "red_flags_raised": [],
            },
            {
                "quarter": "Q1 FY2026", "date": "August 2025",
                "guidance_given": ["FY26 revenue ₹7,500–8,000 Cr", "EBITDA margin 25–26%"],
                "guidance_status": "Met — FY26 revenue ₹7,900 Cr; EBITDA 26%",
                "key_notes": [
                    "KKR retains 30%+ stake — strong institutional shareholder confidence",
                    "ESG: Published first integrated annual report; diversity targets set",
                    "Patient experience NPS score 68 — highest in listed hospital sector",
                ],
                "red_flags_raised": [],
            },
        ],
        "ai_analysis": {
            "bull_factors": [
                "Highest occupancy (76%) and ARPOB (₹77,000) among listed hospital peers — quality premium",
                "North India monopoly — no comparable quality competitor in NCR space",
                "Management track record — Abhay Soi's turnaround from loss-making to ₹1,343 Cr PAT in 8 years",
                "Oncology and BMT leadership — highest margin clinical programs growing fastest",
                "Bed expansion (4,000 beds by FY28) will nearly double capacity with less capital than new hospitals",
            ],
            "bear_factors": [
                "Geographic concentration — 70% revenue from Delhi-NCR; any NCR disruption is material",
                "Mumbai entry is high-risk — competitive market with Apollo, Fortis, Kokilaben established",
                "Rising debt (₹4,500 Cr) from expansion capex — interest burden growing",
                "Promoter (KKR) is PE — eventual exit creates shareholder overhang",
            ],
            "red_flags": [
                "KKR stake overhang — PE exit could cause supply-side pressure on stock",
                "Mumbai acquisition execution risk — Lifeline is a turn-around story",
                "Staff attrition at 12% — clinical staff (especially oncology) hard to replace",
                "New bed ramp-up: First 2-3 years of any new hospital are EBITDA-dilutive",
            ],
            "overall_score": 8.4,
            "recommendation": "BUY — Best-in-class operations, ARPOB growth, and occupancy. Premium justified. Entry on dips.",
        }
    },

    "LAURUS": {
        "name": "Laurus Labs Limited",
        "ticker": "LAURUSLABS.NS",
        "type": "pharma",
        "hq": "Hyderabad, Telangana",
        "founded": 2005,
        "market_cap_cr": 87000,
        "cmp": 466,
        "description": "One of India's leading API and CDMO companies with strong presence in ARV (antiretroviral), oncology APIs, and contract manufacturing. Transitioning from API to high-value finished dosage and CDMO.",
        "facilities": [
            {"city": "Visakhapatnam, AP (Parawada)", "type": "API + FDF + CDMO", "count": 6, "status": "Operational"},
            {"city": "Vizag (Unit 7 + R&D)", "type": "CDMO/FDF", "count": 2, "status": "Operational"},
            {"city": "Hyderabad (Genome Valley)", "type": "Bio-CDMO (LSIL)", "count": 1, "status": "Operational"},
        ],
        "total_facilities": 12,
        "total_countries": 50,
        "expansion_plans": [
            "LSIL (Laurus Synthesis India Limited) Bio-CDMO — ₹2,000 Cr investment in mammalian cell culture",
            "New CDMO capacity for peptides and oligonucleotides — ₹800 Cr investment",
            "Unit 7 FDF facility expansion — targeting regulated market launches",
            "Building dedicated oncology API block — ₹500 Cr investment",
            "Generic finished dosages (FDF) in US — 30+ products by FY27",
        ],
        "board_members": [
            {"name": "Dr. Satyanarayana Chava", "role": "Founder & CEO", "joined_org": 2005, "joined_board": 2005,
             "background": "PhD Organic Chemistry. Former President at Matrix Laboratories. Built Laurus into a $1 Bn revenue company in under 20 years."},
            {"name": "V.V. Ravi Kumar", "role": "Executive Director & CFO", "joined_org": 2006, "joined_board": 2018,
             "background": "CA with 20+ years. Co-founder of Laurus. Oversees all financial and investor relations."},
            {"name": "Dr. Chandrakanth Chereddi", "role": "Executive Director (API Business)", "joined_org": 2012, "joined_board": 2020,
             "background": "PhD. Earlier with Mylan. Leads API and active pharmaceutical ingredient strategy."},
        ],
        "products": {
            "categories": ["ARV APIs", "Oncology APIs", "Other APIs", "Finished Dosage Forms (FDF)", "CDMO (Synthesis)", "LSIL (Bio-CDMO)"],
            "key_drugs": [
                {"name": "Efavirenz API", "segment": "ARV/HIV", "patent_status": "Generic", "stage": "Marketed (Global)", "revenue_contribution": "High"},
                {"name": "Tenofovir DF API", "segment": "ARV/HIV", "patent_status": "Generic", "stage": "Marketed", "revenue_contribution": "High"},
                {"name": "Dolutegravir API", "segment": "ARV/HIV (INI)", "patent_status": "Licensed from ViiV", "stage": "Marketed", "revenue_contribution": "Very High"},
                {"name": "Lenalidomide API (Oncology)", "segment": "Oncology", "patent_status": "Generic", "stage": "Marketed", "revenue_contribution": "Growing"},
                {"name": "Sofosbuvir API (HCV)", "segment": "Hepatitis C", "patent_status": "Licensed", "stage": "Marketed (EM)", "revenue_contribution": "Moderate"},
                {"name": "Nimotuzumab (Anti-EGFR)", "segment": "Oncology (Bio)", "patent_status": "Licensed from Biocon", "stage": "Development/Clinical", "revenue_contribution": "Pipeline"},
                {"name": "Peptide APIs", "segment": "Peptides", "patent_status": "Process patents being filed", "stage": "Development", "revenue_contribution": "Pipeline"},
            ],
            "pending_patents": ["Novel ARV fixed-dose combinations", "Oncology API process patents", "Peptide synthesis IP"],
            "pipeline_summary": "60+ ANDA filings in US; CDMO pipeline with 15+ multinational clients; Bio-CDMO for mAbs and peptides",
        },
        "supply_chain": {
            "api_sourcing": "Highly backward integrated for ARV APIs; CDMO clients supply starting materials",
            "key_raw_materials": ["ARV starting materials (India-sourced)", "Oncology intermediates"],
            "logistics": "Direct supply to PEPFAR program (US government HIV initiative) via Unitaid",
            "key_markets": ["Africa (ARV) (38%)", "USA (23%)", "EU (15%)", "India (15%)", "RoW (9%)"],
            "china_exposure": "Low-Moderate — reducing through backward integration",
        },
        "revenue_mix": {
            "FY2024": {"ARV APIs": 38, "Other APIs/Oncology": 20, "FDF/Finished Dosage": 22, "CDMO": 15, "LSIL/Bio": 5},
            "FY2025": {"ARV APIs": 32, "Other APIs/Oncology": 22, "FDF/Finished Dosage": 24, "CDMO": 17, "LSIL/Bio": 5},
            "FY2026": {"ARV APIs": 28, "Other APIs/Oncology": 22, "FDF/Finished Dosage": 26, "CDMO": 19, "LSIL/Bio": 5},
        },
        "financials": {
            "FY2024": {"revenue": 5200, "ebitda": 884, "pat": 350, "ebitda_margin": 17.0, "pat_margin": 6.7,
                       "gross_debt": 2800, "cash": 600, "roce": 12.5, "roe": 14.2, "eps": 6.5},
            "FY2025": {"revenue": 6100, "ebitda": 1159, "pat": 550, "ebitda_margin": 19.0, "pat_margin": 9.0,
                       "gross_debt": 3100, "cash": 900, "roce": 14.8, "roe": 15.8, "eps": 10.2},
            "FY2026": {"revenue": 7200, "ebitda": 1548, "pat": 820, "ebitda_margin": 21.5, "pat_margin": 11.4,
                       "gross_debt": 3500, "cash": 1200, "roce": 17.2, "roe": 17.5, "eps": 15.2},
        },
        "concalls": [
            {
                "quarter": "Q4 FY2026", "date": "May 2026",
                "guidance_given": ["FY27 revenue ₹7,500–8,500 Cr", "EBITDA margins 22–24%", "CDMO growing 25%+"],
                "guidance_status": "In progress",
                "key_notes": [
                    "CDMO business growing strongly — 5 new contracts signed with top pharma companies",
                    "FDF (finished dosage) segment turned profitable — margins improving to 18%+",
                    "LSIL (Bio-CDMO) — first mammalian cell culture order received",
                    "US ARV tender (PEPFAR) renewed for 3 years — revenue visibility secured",
                    "ARV mix declining (revenue-share basis) as other segments grow faster",
                ],
                "red_flags_raised": ["Debt/Equity at 1.8x — highest leverage among API peers", "Bio-CDMO LSIL taking longer than expected to monetize"],
            },
            {
                "quarter": "Q3 FY2026", "date": "February 2026",
                "guidance_given": ["CDMO order book growing", "Margins recovering from H1 seasonality"],
                "guidance_status": "Met — CDMO order book grew 35%; margins recovered 150bps QoQ",
                "key_notes": [
                    "10+ new CDMO contracts signed — moving up value chain to drug substance",
                    "Oncology APIs growing 40% YoY — Lenalidomide major contributor",
                    "ARV price erosion contained at 3–5% annually",
                ],
                "red_flags_raised": ["High capex year — FCF negative; debt rising"],
            },
            {
                "quarter": "Q2 FY2026", "date": "November 2025",
                "guidance_given": ["LSIL to show revenue by H2 FY26", "FDF US launches begin FY27"],
                "guidance_status": "Partially met — LSIL first order in Q3; FDF US launch pending approvals",
                "key_notes": [
                    "Peptide manufacturing partnership with European CDMO — technology transfer complete",
                    "ARV finished dosage: 12 products registered in Africa by MedSAID",
                ],
                "red_flags_raised": ["FDF US approvals slower than guided", "LSIL commercialization delayed by 2 quarters"],
            },
            {
                "quarter": "Q1 FY2026", "date": "August 2025",
                "guidance_given": ["FY26 revenue ₹6,500–7,500 Cr", "EBITDA 20–22%"],
                "guidance_status": "Exceeded — FY26 revenue ₹7,200 Cr; EBITDA 21.5%",
                "key_notes": [
                    "CDMO strategy gaining traction — number of innovator clients growing",
                    "Grandfathered PEPFAR position providing stable ARV base",
                ],
                "red_flags_raised": [],
            },
        ],
        "ai_analysis": {
            "bull_factors": [
                "CDMO business growing 25%+ — high-margin, long-cycle contracts reducing earnings volatility",
                "ARV base provides predictable cash flows — PEPFAR multi-year contracts",
                "Bio-CDMO (LSIL) is a $5 Bn TAM play — currently embryonic but strategically sound",
                "Oncology API momentum — Lenalidomide, Pomalidomide demand growing strongly",
                "Management capital allocation improving — FDF segment turning profitable",
            ],
            "bear_factors": [
                "High debt (D/E 1.8x) — most leveraged among API/CDMO peers; interest cost rising",
                "Bio-CDMO (LSIL) investment ₹2,000 Cr with 3–5 year payback — capital intensive",
                "ARV market (28% revenue) faces structural volume pressure as HIV becomes chronic disease",
                "FDF US launches behind schedule — regulatory approval delays",
            ],
            "red_flags": [
                "DEBT: Net D/E 1.8x is a concern; FCF negative in FY26 due to capex",
                "LSIL delays — Bio-CDMO commercialization 2 quarters behind plan",
                "PEPFAR policy risk — US government ARV program subject to budget/policy changes",
                "Promoter holdings declining slightly — track for any further reduction",
            ],
            "overall_score": 6.9,
            "recommendation": "HOLD — Good strategy; execution needs to materialize. Watch debt reduction and CDMO ramp.",
        }
    },

    "FORTIS": {
        "name": "Fortis Healthcare Limited",
        "ticker": "FORTIS.NS",
        "type": "hospital",
        "hq": "Gurugram, Haryana",
        "founded": 2001,
        "market_cap_cr": 44000,
        "cmp": 580,
        "description": "Pan-India hospital network with presence in metro and Tier-1 cities. Acquired and turned around by IHH Healthcare (Malaysia). Focused on clinical excellence and operational efficiency improvement.",
        "facilities": [
            {"city": "Gurugram, Haryana", "type": "Multi-specialty Hospital", "count": 2, "status": "Operational"},
            {"city": "Delhi (Vasant Kunj, Shalimar Bagh)", "type": "Hospital", "count": 2, "status": "Operational"},
            {"city": "Noida, UP", "type": "Multi-specialty Hospital", "count": 1, "status": "Operational"},
            {"city": "Mohali, Punjab", "type": "Multi-specialty Hospital", "count": 1, "status": "Operational"},
            {"city": "Bengaluru, Karnataka", "type": "Multi-specialty Hospital", "count": 2, "status": "Operational"},
            {"city": "Mumbai (Mulund, Kalyan)", "type": "Hospital", "count": 2, "status": "Operational"},
            {"city": "Kolkata, West Bengal", "type": "Hospital", "count": 1, "status": "Operational"},
            {"city": "Jaipur, Rajasthan", "type": "Hospital", "count": 1, "status": "Operational"},
        ],
        "total_facilities": 27,
        "total_beds": 4400,
        "total_countries": 1,
        "expansion_plans": [
            "IHH Strategic support — 3,000 new beds planned by FY28",
            "New hospital in Ludhiana — 400 beds, FY27 target",
            "SRL Diagnostics acquisition reversed; focusing on core hospitals",
            "OP Jindal Cancer Centre — 300-bed oncology specialty hospital",
            "Technology-first hospitals — AI-based diagnostics and robotic surgeries",
        ],
        "board_members": [
            {"name": "Ashutosh Raghuvanshi", "role": "MD & CEO", "joined_org": 2019, "joined_board": 2019,
             "background": "Former CMD of Narayana Hrudayalaya. Cardiologist by training. Led NH from 2 to 50+ hospitals. Bringing similar playbook to Fortis — volume-led growth with cost discipline."},
            {"name": "Vivek Goyal", "role": "CFO", "joined_org": 2019, "joined_board": None,
             "background": "CA. Earlier CFO at DLF and Max Financial. Deep financial restructuring expertise."},
            {"name": "Ravi Rajagopal", "role": "Non-Executive Chairman", "joined_org": None, "joined_board": 2018,
             "background": "Former senior executive at Jardine Matheson. Represents IHH Healthcare's board interests."},
        ],
        "products": {
            "categories": ["Hospital (Inpatient)", "Emergency & Trauma", "Oncology", "Cardiac", "Orthopaedics"],
            "key_services": [
                {"name": "Cardiac Sciences", "segment": "Clinical", "revenue_contribution": "Highest"},
                {"name": "Oncology (Fortis Cancer Institute)", "segment": "Clinical", "revenue_contribution": "High"},
                {"name": "Emergency & Trauma", "segment": "Clinical", "revenue_contribution": "High"},
                {"name": "Robotic Surgery", "segment": "Technology", "revenue_contribution": "Growing"},
            ],
        },
        "supply_chain": {
            "api_sourcing": "N/A",
            "key_raw_materials": ["Medical devices", "Oncology drugs", "Consumables"],
            "logistics": "Centralized procurement under IHH group synergies",
            "key_markets": ["India (100%)"],
            "china_exposure": "Low",
        },
        "revenue_mix": {
            "FY2024": {"North India Hospitals": 45, "South India Hospitals": 25, "West India": 20, "East India": 10},
            "FY2025": {"North India Hospitals": 44, "South India Hospitals": 26, "West India": 20, "East India": 10},
            "FY2026": {"North India Hospitals": 43, "South India Hospitals": 27, "West India": 21, "East India": 9},
        },
        "financials": {
            "FY2024": {"revenue": 7069, "ebitda": 1272, "pat": 636, "ebitda_margin": 18.0, "pat_margin": 9.0,
                       "gross_debt": 3800, "cash": 1900, "roce": 14.5, "roe": 15.2, "eps": 8.4},
            "FY2025": {"revenue": 8139, "ebitda": 1547, "pat": 826, "ebitda_margin": 19.0, "pat_margin": 10.2,
                       "gross_debt": 3500, "cash": 2300, "roce": 16.2, "roe": 16.5, "eps": 10.9},
            "FY2026": {"revenue": 9350, "ebitda": 1870, "pat": 1028, "ebitda_margin": 20.0, "pat_margin": 11.0,
                       "gross_debt": 3200, "cash": 2900, "roce": 18.0, "roe": 18.0, "eps": 13.5},
        },
        "hospital_ratios": {
            "FY2024": {
                "occupancy_rate": 63.0,
                "arpob_per_day": 48500,
                "alos_days": 3.6,
                "beds_operational": 3800,
                "inpatient_volume": 325000,
                "outpatient_volume": 5100000,
                "revenue_per_bed_cr": 0.285,
                "ebitda_per_bed_lakh": 5.1,
                "doctor_count": 4200,
                "nursing_ratio": 2.8,
            },
            "FY2025": {
                "occupancy_rate": 66.5,
                "arpob_per_day": 54000,
                "alos_days": 3.5,
                "beds_operational": 4100,
                "inpatient_volume": 365000,
                "outpatient_volume": 5800000,
                "revenue_per_bed_cr": 0.310,
                "ebitda_per_bed_lakh": 5.9,
                "doctor_count": 4600,
                "nursing_ratio": 2.9,
            },
            "FY2026": {
                "occupancy_rate": 69.5,
                "arpob_per_day": 60000,
                "alos_days": 3.4,
                "beds_operational": 4400,
                "inpatient_volume": 410000,
                "outpatient_volume": 6500000,
                "revenue_per_bed_cr": 0.336,
                "ebitda_per_bed_lakh": 6.7,
                "doctor_count": 5000,
                "nursing_ratio": 3.0,
            },
        },
        "concalls": [
            {
                "quarter": "Q4 FY2026", "date": "May 2026",
                "guidance_given": ["Revenue growth 15% in FY27", "EBITDA margin 21%+", "ARPOB ₹65,000 by FY27-end"],
                "guidance_status": "In progress",
                "key_notes": [
                    "IHH synergies materializing — procurement savings of ₹150 Cr annually",
                    "Ashutosh Raghuvanshi's turnaround on track: ARPOB grew 11% to ₹60,000",
                    "Oncology program receiving traction — cancer surgeries up 30% YoY",
                    "North India hospitals occupancy reached 72% — near full utilization",
                ],
                "red_flags_raised": ["South India hospitals still underperforming — ARPOB 20% below North India", "IHH rights issue — existing shareholders risk dilution"],
            },
            {
                "quarter": "Q3 FY2026", "date": "February 2026",
                "guidance_given": ["ARPOB to cross ₹57,000", "Occupancy 68%+"],
                "guidance_status": "Met — ARPOB ₹58,500; Occupancy 68.8%",
                "key_notes": [
                    "Acquired Vardhman Hospital (Ludhiana) — 250 beds, expansion to 400",
                    "International JCI accreditation for 7 more hospitals",
                    "Rohtak hospital to be operationalized by Q1 FY27",
                ],
                "red_flags_raised": ["Seasonal Q3 weakness in south India hospitals"],
            },
            {
                "quarter": "Q2 FY2026", "date": "November 2025",
                "guidance_given": ["PAT margins to sustain 10%+", "New beds to be margin-accretive"],
                "guidance_status": "Met — PAT margin 11%; new beds adding EBITDA above average",
                "key_notes": [
                    "Robotic surgery: 6 Da Vinci systems across network — highest Fortis investment",
                    "Fortis digital app — 2.5 Mn downloads, growing 40% QoQ",
                    "Employee satisfaction improved — attrition fell to 14% from 20%",
                ],
                "red_flags_raised": [],
            },
            {
                "quarter": "Q1 FY2026", "date": "August 2025",
                "guidance_given": ["FY26 revenue ₹9,000–10,000 Cr", "EBITDA margin 19–21%"],
                "guidance_status": "Met — FY26 revenue ₹9,350 Cr; EBITDA 20%",
                "key_notes": [
                    "New management (Raghuvanshi) delivering consistent improvement for 5th consecutive year",
                    "IHH capital support for capex — parental backing reduces funding risk",
                ],
                "red_flags_raised": ["Historical governance issues (Singh brothers era) — legacy caution"],
            },
        ],
        "ai_analysis": {
            "bull_factors": [
                "IHH Healthcare (Malaysia) parental backing — provides capital, technology, and governance",
                "CEO Raghuvanshi track record at NH — systematic ARPOB and occupancy improvement",
                "North India hospitals performing near-peak — South India is the upside catalyst",
                "Consistent ARPOB growth (8-11% YoY) — pricing power improving",
                "Oncology program traction — margin-accretive surgeries growing",
            ],
            "bear_factors": [
                "Legacy governance issues (Singh brothers era) — lingering regulatory/legal matters",
                "South India hospitals lagging — ARPOB 20% below North India peers",
                "High debt relative to scale — net D/E 0.8x",
                "IHH parent might delist — overhang on minority shareholders",
            ],
            "red_flags": [
                "LEGACY RISK: Singh brothers era liabilities — some cases still pending in courts",
                "IHH rights issue/buyout possibility — minority shareholder interest risk",
                "South India hospital performance — consistent underperformance vs peers",
                "Older hospital infrastructure — capex needed but IHH-led",
            ],
            "overall_score": 6.8,
            "recommendation": "HOLD — Turnaround on track but discount to Max/Apollo justified. Watch South India recovery.",
        }
    },
}

SECTOR_TYPES = {"pharma": "Pharmaceuticals / CRDMO", "hospital": "Hospitals / Healthcare Services"}

def get_all_companies():
    return {k: {"name": v["name"], "type": v["type"], "hq": v["hq"]} for k, v in COMPANIES.items()}

def get_company_data(ticker_key):
    return COMPANIES.get(ticker_key, None)
